<div class="container">

	<div class="page-header">
	  <h4>OFFRES</h4>
	</div>

	<form class="form-inline right">
		<div class="form-group">
		       <input type="text" class="form-control" placeholder="Quoi ?">
		 </div>
		<div class="form-group">
			 	<input type="text" class="form-control" placeholder="Où ?">
	    </div>
		<button type="submit" class="btn btn-default">Go !</button>
	</form>

	<br><br>

	<div class="row">
	  <div class="col-sm-4">
		  <div class="panel panel-default">
			  <div class="panel-heading">Experience</div>
			  <div class="panel-body">
			<h6> Recherche similaires </h6>
			<div class="search">
				<p> Blooooooo </p>
			</div>
			</div>

  		<div class="panel-heading">Type de contrat</div>
		<div class="panel-body">
			<h6> Recherche similaires </h6>
			<div class="search">
				<p> Bluuuuurrrr </p>
			</div>
		</div>

		<div class="panel-heading">Type de société</div>
		<div class="panel-body">
			<div class="search">
				<p> Blizzzaaaa </p>
			</div>
		</div>

		<div class="panel-heading">Recherches similaires</div>
		<div class="panel-body">
			<div class="search">
				<p> hé ouais grow </p>
			</div>
		</div>


		<div class="panel-heading">Ils recherchent des talents</div>
			<div class="row">
						  <br><br>
				<div class="col-sm-3">
					<a href="#" class="thumbnail">
						<img src="http://placehold.it/70x70">
					</a>
			   </div>
				<div class="col-sm-3">
					<a href="#" class="thumbnail">
						<img src="http://placehold.it/70x70">
					</a>
			   </div>
			   <div class="col-sm-3">
				   <a href="#" class="thumbnail">
					   <img src="http://placehold.it/70x70">
				   </a>
			  </div>
			</div>
			<div class="row">
				<div class="col-sm-3">
					<a href="#" class="thumbnail">
						<img src="http://placehold.it/70x70">
					</a>
			   </div>
				<div class="col-sm-3">
					<a href="#" class="thumbnail">
						<img src="http://placehold.it/70x70">
					</a>
			   </div>
			   <div class="col-sm-3">
				   <a href="#" class="thumbnail">
					   <img src="http://placehold.it/70x70">
				   </a>
			  	</div>
				</div>
			</div>
		</div>


	  <div class="col-sm-8">

		<div class="panel panel-default">
		  <div class="panel-heading">Enonce de l'offre</div>
		  <div class="panel-body">
		    Contenus et description de l'offre
			<br><br>
			Contenus et description de l'offre
			Contenus et description de l'offre
		  </div>
		</div>

		<div class="panel panel-default">
		  <div class="panel-heading">Enonce de l'offre</div>
			  <div class="panel-body">
				Contenus et description de l'offre
					<br><br>
				Contenus et description de l'offre
				Contenus et description de l'offre
			  </div>
		</div>

		<div class="panel panel-default">
		  <div class="panel-heading">Enonce de l'offre</div>
			  <div class="panel-body">
				<p>Contenus et description de l'offre</p>

<?php var_dump($annonce);  ?>

			  </div>
		</div>

	 </div>
</div>



	<nav>
		<ul class="pager">
			<li><a href="#"><</a></li>
			<li><a href="#">></a></li>
		</ul>
	</nav>

</div>
